In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols

### Z-Test

In [2]:
debit_card_spending = np.array([7960, 7700, 7727, 7704, 8543, 7661, 7767, 8761, 7530, 8128,
                               7938, 7771, 7272, 8113, 7727, 7697, 7690, 8000, 8079, 7547])

$ H_0: \mu \geq 8,000 $ <br>
$ H_a: \mu < 8,000 $ 

In [7]:
sm.stats.ztest(debit_card_spending, value=8000, alternative='smaller')

(-1.7459672258178607, 0.04040832351015883)

#### Population Proportion z-test

In [11]:
#Q. 9.4 - 60 Book

In [12]:
sm.stats.proportions_ztest(20, 66, value=0.32) # a

(-0.2999826081915271, 0.7641904217043829)

In [13]:
sm.stats.proportions_ztest(100, 264, value=0.32) # b

(1.9691180643169954, 0.04893953491647526)

In [14]:
p = 0.40
n = 40
sm.stats.proportions_ztest(int(p*n), n, value=0.32) # c

(1.0327955589886446, 0.30169958247834794)

In [15]:
p = 0.38
n = 180
sm.stats.proportions_ztest(int(p*n), n, value=0.32) # d

(1.5988441202970356, 0.10985524288571252)

### T-Test

In [8]:
# weekly average study data

data = np.array([25,19,26,11,29,
                17,16,14,21,10,
                8,9,22,6,10,
                14,15,17,20,4,
                17,12,14,27,25,
                7,17,35,17,13,
                11,19,24,6,16])

$ H_0: \mu \geq 24 $ <br>
$ H_a: \mu < 24 $ 

In [9]:
stats.ttest_1samp(data, popmean=24, alternative='less')

Ttest_1sampResult(statistic=-6.254736729185618, pvalue=2.0146379463385562e-07)

In [16]:
# Q. 

data = np.array([22,62,62,29,20,52,
                36,53,44,38,72,28,
                78,26,51,46,41,69,
                103,28,38,52,73,27,
                38,25,77,61,16,53,
                43,31,37,57,32,46])

$ H_0: \mu \geq 49 $ <br>
$ H_a: \mu < 49 $ 

In [17]:
stats.ttest_1samp(data, popmean=49, alternative='less')

Ttest_1sampResult(statistic=-0.8365868588713955, pvalue=0.20425029285536012)

$ H_0: \bar p \leq 0.20 $ <br>
$ H_a: \bar p > 0.20 $ 

In [21]:
p = len(data[data<30]) / len(data)
p

0.25

In [29]:
sm.stats.proportions_ztest(len(data[data<30]), len(data), value=0.20, alternative='larger')

(0.6928203230275508, 0.2442111583112968)

### Comparisions involving Means

#### Two indepedent Samples

In [30]:
dataframe = pd.DataFrame({'gold':[6,15,19,26,2,16,31,14,15,16],
                         'oil':[-3,15,28,18,32,31,15,12,10,15]})
dataframe

gold  oil
0     6   -3
1    15   15
2    19   28
3    26   18
4     2   32
5    16   31
6    31   15
7    14   12
8    15   10
9    16   15

In [31]:
# null hypothesis : mean1 - mean2 = 0
# alt hypothesis : mean1 - mean2 != 0

## two-sided t-test
stats.ttest_ind(dataframe.gold, dataframe.oil, equal_var=False) ## two-sample with unequal varince

Ttest_indResult(statistic=-0.30232558139534904, pvalue=0.766060177642123)

#### Dependent Sampling (Matched-pairs sampling)

In [33]:
df = pd.DataFrame({'end':[64,54,126,97,37,74,117,90,81],
                  'middle':[72,41,100,62,40,60,122,62,78]})
df

end  middle
0   64      72
1   54      41
2  126     100
3   97      62
4   37      40
5   74      60
6  117     122
7   90      62
8   81      78

In [35]:
stats.ttest_rel(df.end, df.middle, alternative='greater')

Ttest_relResult(statistic=2.1833503263322047, pvalue=0.030272709245538383)

### ANOVA


- https://www.reneshbedre.com/blog/anova.html

#### 1. One way anova test

In [37]:
smartphones = pd.DataFrame({'iphone':[87,85,78,82],
                           'galaxy':[71, 82, 75, 80],
                           'moto':[66, 74, 79, np.nan],
                           'lgg7':[65,69,67,63]})

smartphones

iphone  galaxy  moto  lgg7
0      87      71  66.0    65
1      85      82  74.0    69
2      78      75  79.0    67
3      82      80   NaN    63

null hypothesis: All means are same <br>
alt hypothesis: not same

In [41]:
rv = stats.f_oneway(smartphones.iphone, smartphones.galaxy, smartphones.moto.dropna(), smartphones.lgg7)
rv

F_onewayResult(statistic=9.859980334316617, pvalue=0.001887232383275623)

At 95% percent confidence we can reject the null hypothesis. <br>
There is difference is means <br> <br>

**Tukey–Kramer Multiple Comparison Test for One-Way ANOVA** allows us to examine each pair of sample means and to conclude whether their respective population means differ for one-way ANOVA.

In [20]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison

In [69]:
df = smartphones.melt(value_vars=smartphones.columns.to_list(), value_name='total', var_name='company')
df

company  total
0   iphone   87.0
1   iphone   85.0
2   iphone   78.0
3   iphone   82.0
4   galaxy   71.0
5   galaxy   82.0
6   galaxy   75.0
7   galaxy   80.0
8     moto   66.0
9     moto   74.0
10    moto   79.0
11    moto    NaN
12    lgg7   65.0
13    lgg7   69.0
14    lgg7   67.0
15    lgg7   63.0

In [73]:
res = pairwise_tukeyhsd(df.total.dropna(), df.company[df.total.notna()])

In [74]:
res.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [2]:
df = pd.DataFrame({'driver1':[40,32,28,29,40],
                  'driver2':[16,9,13,22,np.nan],
                  'driver3':[27, 24,13,9,10],
                  'driver4':[21,7,34,14,np.nan]})
df

driver1  driver2  driver3  driver4
0       40     16.0       27     21.0
1       32      9.0       24      7.0
2       28     13.0       13     34.0
3       29     22.0        9     14.0
4       40      NaN       10      NaN

In [3]:
stats.f_oneway(df.driver1,
              df.driver2.dropna(),
              df.driver3,
              df.driver4.dropna())

F_onewayResult(statistic=5.53814568448715, pvalue=0.010169306437949461)

In [7]:
df2 = df.melt(value_name='time', value_vars=df.columns.to_list(), var_name='driver')
df2 = df2.dropna()
df2

driver  time
0   driver1  40.0
1   driver1  32.0
2   driver1  28.0
3   driver1  29.0
4   driver1  40.0
5   driver2  16.0
6   driver2   9.0
7   driver2  13.0
8   driver2  22.0
10  driver3  27.0
11  driver3  24.0
12  driver3  13.0
13  driver3   9.0
14  driver3  10.0
15  driver4  21.0
16  driver4   7.0
17  driver4  34.0
18  driver4  14.0

In [9]:
tukey = sm.stats.multicomp.pairwise_tukeyhsd(df2.time, df2.driver)

print(tukey.summary())

  Multiple Comparison of Means - Tukey HSD, FWER=0.05  
 group1  group2 meandiff p-adj   lower    upper  reject
-------------------------------------------------------
driver1 driver2    -18.8 0.0168 -34.4521 -3.1479   True
driver1 driver3    -17.2 0.0204  -31.957  -2.443   True
driver1 driver4    -14.8 0.0667 -30.4521  0.8521  False
driver2 driver3      1.6    0.9 -14.0521 17.2521  False
driver2 driver4      4.0 0.8914 -12.4988 20.4988  False
driver3 driver4      2.4    0.9 -13.2521 18.0521  False
-------------------------------------------------------


In [10]:
from statsmodels.formula.api import ols

In [11]:
model = ols('time ~ C(driver)', data=df2).fit()

In [13]:
anova_table = sm.stats.anova_lm(model,typ=1)
anova_table

df       sum_sq     mean_sq         F    PR(>F)
C(driver)   3.0  1070.444444  356.814815  5.538146  0.010169
Residual   14.0   902.000000   64.428571       NaN       NaN

In [14]:
## Bartlett test for eual variance
## H0: All variance are equal
## Ha: not equal

stats.bartlett(df.driver1,
              df.driver2.dropna(),
              df.driver3,
              df.driver4.dropna())

BartlettResult(statistic=2.1111007320751347, pvalue=0.549670276240217)

#### 2. Two-way Anova test

In [15]:
dataset = pd.read_csv("https://reneshbedre.github.io/assets/posts/anova/twowayanova.txt", sep="\t")
dataset

Genotype  1_year  2_year  3_year
0         A    1.53    4.08    6.69
1         A    1.83    3.84    5.97
2         A    1.38    3.96    6.33
3         B    3.60    5.70    8.55
4         B    2.94    5.07    7.95
5         B    4.02    7.20    8.94
6         C    3.99    6.09   10.02
7         C    3.30    5.88    9.63
8         C    4.41    6.51   10.38
9         D    3.75    5.19   11.40
10        D    3.63    5.37    9.66
11        D    3.57    5.55   10.53
12        E    1.71    3.60    6.87
13        E    2.01    5.10    6.93
14        E    2.04    6.99    6.84
15        F    3.96    5.25    9.84
16        F    4.77    5.28    9.87
17        F    4.65    5.07   10.08

In [17]:
dataset = dataset.melt(id_vars=['Genotype'], value_vars=['1_year', '2_year', '3_year'],
            value_name='years')

dataset

Genotype variable  years
0         A   1_year   1.53
1         A   1_year   1.83
2         A   1_year   1.38
3         B   1_year   3.60
4         B   1_year   2.94
5         B   1_year   4.02
6         C   1_year   3.99
7         C   1_year   3.30
8         C   1_year   4.41
9         D   1_year   3.75
10        D   1_year   3.63
11        D   1_year   3.57
12        E   1_year   1.71
13        E   1_year   2.01
14        E   1_year   2.04
15        F   1_year   3.96
16        F   1_year   4.77
17        F   1_year   4.65
18        A   2_year   4.08
19        A   2_year   3.84
20        A   2_year   3.96
21        B   2_year   5.70
22        B   2_year   5.07
23        B   2_year   7.20
24        C   2_year   6.09
25        C   2_year   5.88
26        C   2_year   6.51
27        D   2_year   5.19
28        D   2_year   5.37
29        D   2_year   5.55
30        E   2_year   3.60
31        E   2_year   5.10
32        E   2_year   6.99
33        F   2_year   5.25
34        F   2_year   5.28
35        F   2_year   5.07
36        A   3_year   6.69
37        A   3_year   5.97
38        A   3_year   6.33
39        B   3_year   8.55
40        B   3_year   7.95
41        B   3_year   8.94
42        C   3_year  10.02
43        C   3_year   9.63
44        C   3_year  10.38
45        D   3_year  11.40
46        D   3_year   9.66
47        D   3_year  10.53
48        E   3_year   6.87
49        E   3_year   6.93
50        E   3_year   6.84
51        F   3_year   9.84
52        F   3_year   9.87
53        F   3_year  10.08

In [18]:
model = ols('years ~ C(Genotype) + C(variable) + C(Genotype):C(variable)', data=dataset).fit()

In [19]:
sm.stats.anova_lm(model,typ=2)

sum_sq    df           F        PR(>F)
C(Genotype)               58.551733   5.0   32.748581  1.931655e-12
C(variable)              278.925633   2.0  390.014868  4.006243e-25
C(Genotype):C(variable)   17.122967  10.0    4.788525  2.230094e-04
Residual                  12.873000  36.0         NaN           NaN

In [22]:
tukey = pairwise_tukeyhsd(dataset.years, dataset.Genotype)
tukey.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [23]:
tukey = pairwise_tukeyhsd(dataset.years, dataset.variable)
tukey.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [26]:
from bioinfokit.analys import stat

In [34]:
res = stat()
res.tukey_hsd(df=dataset, res_var='years',xfac_var=['Genotype','variable'], anova_model='years~C(Genotype)+C(variable)')

res.tukey_summary

group1       group2  Diff     Lower     Upper    q-value   p-value
0    (A, 1_year)  (A, 2_year)  2.38 -0.054792  4.814792   5.104874  0.061992
1    (A, 1_year)  (A, 3_year)  4.75  2.315208  7.184792  10.188300  0.001000
2    (A, 1_year)  (B, 1_year)  1.94 -0.494792  4.374792   4.161116  0.270409
3    (A, 1_year)  (B, 2_year)  4.41  1.975208  6.844792   9.459032  0.001000
4    (A, 1_year)  (B, 3_year)  6.90  4.465208  9.334792  14.799846  0.001000
..           ...          ...   ...       ...       ...        ...       ...
148  (E, 3_year)  (F, 2_year)  1.68 -0.754792  4.114792   3.603441  0.508206
149  (E, 3_year)  (F, 3_year)  3.05  0.615208  5.484792   6.541961  0.003466
150  (F, 1_year)  (F, 2_year)  0.74 -1.694792  3.174792   1.587230  0.900000
151  (F, 1_year)  (F, 3_year)  5.47  3.035208  7.904792  11.732632  0.001000
152  (F, 2_year)  (F, 3_year)  4.73  2.295208  7.164792  10.145402  0.001000

[153 rows x 7 columns]

#### Randomized Anova Test

In [2]:
calls = pd.DataFrame({'day':['mon','tue','wed','thu','fri'],
                     'dan':[5,4,6,6,4],
                     'amy':[8,7,8,7,5],
                     'beth':[8,4,7,5,3]})
calls

day  dan  amy  beth
0  mon    5    8     8
1  tue    4    7     4
2  wed    6    8     7
3  thu    6    7     5
4  fri    4    5     3

In [11]:
## Here the order of day is import

In [5]:
calls = calls.melt(id_vars=['day'], value_vars=['dan','amy','beth'], var_name='name')
calls

day  name  value
0   mon   dan      5
1   tue   dan      4
2   wed   dan      6
3   thu   dan      6
4   fri   dan      4
5   mon   amy      8
6   tue   amy      7
7   wed   amy      8
8   thu   amy      7
9   fri   amy      5
10  mon  beth      8
11  tue  beth      4
12  wed  beth      7
13  thu  beth      5
14  fri  beth      3

In [9]:
model = ols('value ~ C(day) + C(name)', data=calls).fit()

In [10]:
anova_table = sm.stats.anova_lm(model, typ=1)
anova_table

df  sum_sq  mean_sq         F    PR(>F)
C(day)    4.0    20.4     5.10  6.000000  0.015625
C(name)   2.0    11.2     5.60  6.588235  0.020368
Residual  8.0     6.8     0.85       NaN       NaN

## Comparisons Involving Proportions - ChiSqure Test

### 1. Comparing two or more proportions

In [2]:
data = pd.DataFrame({'day':['mon','tue','wed','thu','fri'],
                     'up':[20,15,17,14,12],
                     'down':[5,11,9,11,11]})
data

day  up  down
0  mon  20     5
1  tue  15    11
2  wed  17     9
3  thu  14    11
4  fri  12    11

We are interested in determining if the proportion of “up” days truly differs across days of the week

$$H_0: p_1 = p_2 = p_3 = p_4 = p_5$$
$$H_1: Not all ps are equal $$

In [6]:
stat, pval,(table, expected) =  sm.stats.proportions_chisquare(data.up, data.sum(axis=1))

In [7]:
stat, pval ## cannot reject the null hypothesis

(5.106469646959223, 0.27654646724115983)

In [8]:
table

array([[20,  5],
       [15, 11],
       [17,  9],
       [14, 11],
       [12, 11]], dtype=int64)

In [9]:
expected

array([[15.6  ,  9.4  ],
       [16.224,  9.776],
       [16.224,  9.776],
       [15.6  ,  9.4  ],
       [14.352,  8.648]])

In [10]:
data = pd.DataFrame({'day':[1,2,3,4,5],
                     'market_share2010':[0.40,0.32,0.24,0.02,0.02],
                     'no_recent_customers':[70,60,54,10,6]})
data

day  market_share2010  no_recent_customers
0    1              0.40                   70
1    2              0.32                   60
2    3              0.24                   54
3    4              0.02                   10
4    5              0.02                    6

In [15]:
expected = data.market_share2010*200
expected

0    80.0
1    64.0
2    48.0
3     4.0
4     4.0
Name: market_share2010, dtype: float64

In [20]:
stats.chisquare(data.no_recent_customers, data.market_share2010*200)

Power_divergenceResult(statistic=12.25, pvalue=0.015585874217053057)

In [21]:
data = pd.DataFrame({'gender':['male', 'female'],
                     'mobile':[23,14],
                     'desktop':[31,11]})
data

gender  mobile  desktop
0    male      23       31
1  female      14       11

In [22]:
sm.stats.proportions_chisquare(data.mobile, data.sum(axis=1)) # stat, pval, table, expected

(1.2336712903379567,
 0.2666942457990322,
 (array([[23, 31],
         [14, 11]], dtype=int64),
  array([[25.29113924, 28.70886076],
         [11.70886076, 13.29113924]])))

### 2. Testing the independence of two variables

Suppose Best Buy would like to know if the age of a customer affects the brand of digital camera he or she purchases. This information would be used to help design a new promotional campaign.

In [23]:
data = pd.DataFrame({'age_group':['18-34', '35-51', '52+'],
                    'canon':[30,22,8],
                    'nikon':[16,25,9],
                    'sony':[8,19,13]})
data

age_group  canon  nikon  sony
0     18-34     30     16     8
1     35-51     22     25    19
2       52+      8      9    13

In [25]:
data = data.set_index('age_group')
data

canon  nikon  sony
age_group                    
18-34         30     16     8
35-51         22     25    19
52+            8      9    13

In [26]:
stats.chi2_contingency(data) ## chi2, pval, dof, expected

(12.145454545454545,
 0.01630177772323308,
 4,
 array([[21.6, 18. , 14.4],
        [26.4, 22. , 17.6],
        [12. , 10. ,  8. ]]))

By rejecting the null hypothesis, we have found support that there is a relationship between the age groups of customers and the camera brands they purchase.
At 95% confidence interval we have enough evidence to conclude that the age is dependent on the choice of camera

# Nonparametric Statistics

## ----Wilcoxon Rank-Sum Test

The Wilcoxon rank-sum test is a nonparametric procedure that determines whether two populations have the same probability distribution based on evidence from two independent samples.

In [2]:
a = np.array([24,31,26,33,28,22,27,23])
b = np.array([32,32,29,25,43,35,45])

In [4]:
stats.ranksums(a,b) ## Wilcoxon rank-sum test

RanksumsResult(statistic=-2.1988227369598095, pvalue=0.027890529120246504)

Because we reject the null hypothesis, SallieMae can conclude that the there is a difference in the distributions for the two populations—that is, that the median age of full-time MBA students is different from the median age of part-time MBA students. It appears that full-time students tend to be younger than part-time students.

In [3]:
a = np.array([743,792,798,1260,748,614,709,678,557,952,917])
b = np.array([947,1318,567,465,1137,1442,1229,1122,1421,1152,617,1287])


$H_0: a_{median} \geq b_{median}$ <br>
$H_a: a_{median} < b_{median}$

In [8]:
stat, pval = stats.ranksums(a,b)

stat, pval

(-1.8463723646899908, 0.06483815699206645)

In [7]:
pval/2 # because the pval is two sided

0.032419078496033225

Reject Null Hypothesis

## Wilcoxon signed-rank test
The **Wilcoxon signed-rank test** is a nonparametric procedure that can be used to compare two dependent samples. The populations from which they were drawn need not be normally distributed.

In [9]:
end_aisle = np.array([64,54,126,97,37,74,117,90,81])
middle_aisle = np.array([72,41,100,62,40,60,122,62,78])

H0: End_aisle sales are equal to or less than middle-aisle sales<br>
H1: End_aisle sales exceed middle-aisle sales

In [12]:
stats.wilcoxon(end_aisle,middle_aisle,alternative='greater')

WilcoxonResult(statistic=36.5, pvalue=0.064453125)

## Kruskal–Wallis test
The **Kruskal–Wallis test** is a nonparametric procedure that allows us to determine if there is difference in the medians of three or more populations.

In [13]:
## 401(k) balance by age group

A_50_54 = np.array([157,76,215,235,349])
B_55_59 = np.array([798,296,371,396,129,234])
C_60_64 = np.array([129,571,129,316,253,543,115])

In [14]:
stats.kruskal(A_50_54,B_55_59,C_60_64)

KruskalResult(statistic=1.935642733777443, pvalue=0.3799098212636963)

In [ ]:
# Because we fail to reject the null hypothesis, AARP cannot conclude that 
# the median 401(k) balances for the three age groups are different.

## Spearman Rank-Order Correlation Coefficient

The **Spearman rank-order correlation coefficient**, rS, measures the strength and direction of the relationship between two variables but **only requires the data be at the ordinal level of measurement.**

In [15]:
data = pd.DataFrame({'study_hours':[3,6,4,4,3,2],
                    'grade':[86,95,92,83,78,79]})

data

study_hours  grade
0            3     86
1            6     95
2            4     92
3            4     83
4            3     78
5            2     79

In [18]:
stats.spearmanr(data)

SpearmanrResult(correlation=0.7650368522374495, pvalue=0.0763256359782481)

Because we fail to reject the null hypothesis, we cannot conclude that there is a relationship between the hours of study and exam grade for the student population. You may find this conclusion surprising considering that rS = 0.771. Also, the sample size n = 6 is very small, which makes rejecting the null hypothesis (finding a relationship) less likely. This would be a good place to briefly discuss the logic of the Spearman rankorder correlation coefficient. If the correlation between the two variables is both strong and positive (close to 1.0), we would expect the ranks for each ordered pair to be close to one another. If the correlation between the two variables is both strong and negative (close to -1.0), we would expect the ranks for each ordered pair not to be close to one another.

## Kendall's tau Rank Coefficient

Kendall's tau, a correlation measure for ordinal data.

Kendall's tau is a measure of the correspondence between two rankings.

In [19]:
data = pd.DataFrame({'expert1':[1,2,3,4,5,6,7],
                    'expert2':[1,3,6,2,7,4,5]})
data

expert1  expert2
0        1        1
1        2        3
2        3        6
3        4        2
4        5        7
5        6        4
6        7        5

In [20]:
stats.kendalltau(data.expert1, data.expert2) #absence of association pval > alpha

KendalltauResult(correlation=0.4285714285714286, pvalue=0.2388888888888889)